#!/bin/bash

mpd(){
    mpd=$(mpc current)
    echo -e "MPD: $mpd"
}

ram(){
    ram=$(free -h | awk '/Mem/ { print $7 }')
    echo -e "RAM: $ram"
}

vol(){
    vol=$(amixer get Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "MM" } else { print $2 }}' | head -n 1)
    echo -e "VOL: $vol"
}

wifi(){
    wifi=$(nmcli | sed '1q' | awk '{print $4}')
    [[ -n $wifi ]] && echo -e "WIFI: $wifi" || echo -e "WIFI: DISCONNECTED"
}

#bri(){
    #bri=$(light | cut -d. -f1)
    #echo -e "BRIGHTNESS: $bri"
#}

#bat(){
    #bat=$(acpi | cut -d" " -f 4 | cut -d"," -f 1 )
    #echo -e "BAT $bat"
#}

timedate(){
    time=$(date +"%a %d, %b %Y | %I:%M")
    echo -e "$time"
}

workspaces(){
    workspaceList=$(bspc query -D --names | paste -sd "   ")
    workspace=$(bspc query -D -d --names)
    workspacesI=$(bspc query -D --names | paste -sd "   " | sed 's/I/\[ I \]/')
    workspacesII=$(bspc query -D --names | paste -sd "   " | sed 's/II/\[ II \]/')
    workspacesIII=$(bspc query -D --names | paste -sd "   " | sed 's/III/\[ III \]/')
    workspacesIV=$(bspc query -D --names | paste -sd "   " | sed 's/IV/\[ IV \]/')
    workspacesV=$(bspc query -D --names | paste -sd "   " | sed 's/ V/ \[ V \]/')
    
    case $workspace in
        I)
            echo -e "$workspacesI";;
        II)
            echo -e "$workspacesII";;
        III)
            echo -e "$workspacesIII";;
        IV)
            echo -e "$workspacesIV";;
        V)
            echo -e "$workspacesV";;
    esac

}

SLEEP_SEC=1
while true; do  
    echo -e "%{l} $(workspaces) %{r}%{F#D3869B}[ $(mpd) ]  %{F#FABD2F}[ $(ram) ]  %{F#FB4934}[ $(vol) ]  %{F#83A598}[ $(wifi) ]  %{F#8EC07C}[ $(timedate) ] " 
    sleep $SLEEP_SEC
done
