# Syntax highlighting
# -------------------
"attribute" = { fg = "primary", modifiers = ["bold"] }

"type" = "primary"
"type.enum.variant" = "secondary"

"constructor" = "tertiary"

"constant" = "secondary"
"constant.character" = "secondaryContainer"
"constant.character.escape" = "tertiaryContainer"

"string" = { fg = "tertiary"}
"string.regexp" = { fg = "tertiaryContainer" }
"string.special" = { fg = "tertiary" }
"string.special.symbol" = { fg = "tertiary" }
"string.special.path" = { fg = "secondary", underline = { color = "secondary", style = "line" } }

"path" = { fg = "secondary", underline = { color = "secondary", style = "line" } }

"comment" = { fg = "outline", modifiers = ["italic"] }

"variable" = "onSurface"
"variable.builtin" = "secondary"
"variable.parameter" = { fg = "onSurfaceVariant", modifiers = ["italic"] }
"variable.other.member" = "primary"

"label" = "secondary"

"punctuation" = "outline"

"keyword" = { fg = "primary", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "tertiary", modifiers = ["italic", "bold"] }

"operator" = { fg = "secondary", modifiers = ["bold"] }

"function" = "tertiary"
"function.macro" = "tertiary"

"tag" = "secondary"

"namespace" = { fg = "secondary", modifiers = ["italic"] }

"special" = "secondary"

"markup.heading" = "primary"
"markup.list" = "onSurface"
"markup.bold" = { fg = "secondary", modifiers = ["bold"] }
"markup.italic" = { fg = "secondary", modifiers = ["italic"] }
"markup.link.url" = { fg = "secondary", modifiers = ["italic", "underlined"] }
"markup.link.label" = "primary"
"markup.raw" = "onSurface"
"markup.quote" = "secondary"

"diff.plus" = "plus"
"diff.minus" = "error"
"diff.delta" = "delta"

# User Interface
# --------------
"ui.background" = "none"

"ui.cursor" = { fg = "onSecondary", bg = "secondary" }
"ui.cursor.match" = { fg = "onTertiary", bg = "tertiary", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "onPrimary", bg = "primary" }

"ui.linenr" = { fg = "onSurfaceVariant" }
"ui.linenr.selected" = { fg = "primary" }

"ui.statusline" = { fg = "onSurface", bg = "surfaceContainerLow" }
"ui.statusline.inactive" = { fg = "onSurface", bg = "surfaceContainerLowest" }
"ui.statusline.normal" = { fg = "onPrimary", bg = "primary", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "onTertiary", bg = "tertiary", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "onSecondary", bg = "secondary", modifiers = ["bold"] }

"ui.bufferline" = { fg = "onSurface", bg = "surfaceContainerLowest" }
"ui.bufferline.active" = { fg = "onSurface", bg = "surfaceContainer", underline = { color = "primary", style = "line" } }
"ui.bufferline.background" = { bg = "surfaceContainerLowest" }

"ui.popup" = { fg = "onSurface", bg = "surfaceContainerLow" }

"ui.window" = { fg = "onSurface" }
"ui.help" = { fg = "onSurface", bg = "surfaceContainerLow" }

"ui.text" = { fg = "onBackground" }
"ui.text.focus" = { fg = "onSurface", bg = "surfaceContainer", modifiers = ["bold"] }

"ui.virtual" = "surfaceVariant"
"ui.virtual.ruler" = { bg = "surfaceContainerLow" }
"ui.virtual.indent-guide" = "surfaceVariant"
"ui.virtual.inlay-hint" = { fg = "onSurfaceVariant", bg = "surfaceContainer", modifiers = ["dim"] }
"ui.virtual.jump-label" = { fg = "primary", modifiers = ["bold"] }

"ui.menu" = { fg = "onSurface", bg = "surfaceContainer" }
"ui.menu.selected" = { fg = "onPrimary", bg = "primary", modifiers = ["bold"] }

"ui.selection" = { bg = "primaryContainer", fg = "onPrimaryContainer" }

"ui.highlight" = { bg = "primaryContainer", modifiers = ["bold"] }

"ui.cursorline" = { bg = "surfaceContainerLowest" }
"ui.cursorline.primary" = { bg = "surfaceContainerLow" }
"ui.cursorline.secondary" = { bg = "surfaceContainerLow" }

error = "error"
warning = "warning"
info = "info"
hint = "hint"

"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

[palette]
# Constants to be used in syntax highlighting, not meant for template processor.
warning = "#f9e2af"
info = "#89dceb"
hint = "#94e2d5"
plus = "#a6e3a1"
delta = "#89b4fa"

# Template colors
primary = "#c7bfff"
surfaceTint = "#c7bfff"
onPrimary = "#2f285f"
primaryContainer = "#463f77"
onPrimaryContainer = "#e5deff"

secondary = "#c8c3dc"
onSecondary = "#312e41"
secondaryContainer = "#474459"
onSecondaryContainer = "#e5dff9"

tertiary = "#ecb8ce"
onTertiary = "#482536"
tertiaryContainer = "#613b4d"
onTertiaryContainer = "#ffd8e7"

error = "#ffb4ab"
onError = "#690005"
errorContainer = "#93000a"
onErrorContainer = "#ffdad6"

background = "#141318"
onBackground = "#e5e1e9"
surface = "#141318"
onSurface = "#e5e1e9"
surfaceVariant = "#48464f"
onSurfaceVariant = "#c9c5d0"

outline = "#928f99"
outlineVariant = "#48464f"

surfaceContainerLowest = "#0e0e13"
surfaceContainerLow = "#1c1b20"
surfaceContainer = "#201f25"
surfaceContainerHigh = "#2a292f"
surfaceContainerHighest = "#35343a"
