#!/usr/bin/bash

niriconfig=~/.config/niri/config.kdl

# Change window border colors
sed -i 's/b8bb26/98971a/g' $niriconfig
sed -i 's/83a598/076678/g' $niriconfig

sed -i 's/282828/f2e5bc/g' $niriconfig
