#! /bin/sh

setxkbmap -layout us
setxkbmap -option caps:swapescape
nitrogen --restore
xrdb ~/.Xresources
$HOME/.scripts/natscroll
#$HOME/.config/bspwm/lemonbar | lemonbar -g x18++ -f fixed:size=10:style=bold:antialias=true  -B \#32302f -F \#FBF1c7 -p &
polybar example &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -cf --vsync &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc-bspwm &
dusnt &
xsettingsd &
xfce4-power-manager --daemon &
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'slock' '' &

bspc monitor -d www media prod term game

bspc config border_width           2
bspc config window_gap             10
bspc config normal_border_color    \#32302F
bspc config active_border_color    \#8EC07C
bspc config focused_border_color   \#B8BB26
bspc config presel_feedback_color  \#8EC07C

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
