[colors]
background = "#201f25FF"
text_primary = "#e5e1e9FF"
text_muted = "#c9c5d0FF"
accent_primary = "#c7bfffFF"
accent_secondary = "#c8c3dcFF"
warning = "#ecb8ceFF"
error = "#ffb4abFF"
insert_hint = "#ecb8ce80"
backdrop = "#48464fFF"

[colors.border]
focused = "#c7bfffFF"
unfocused = "#48464fFF"
outer = "#141318FF"

[colors.overview]
background_tint = "#14131888"
badge = "#c7bfffFF"
workspace_background = "#141318FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#ecb8ceFF"
border_color_unfocused = "#613b4dFF"
