[mgr]
prepend_keymap = [
  { on = ";", run = "plugin bunny", desc = "Start bunny.yazi" },
  { on = "'", run = "plugin bunny fuzzy", desc = "Start bunny.yazi fuzzy search" },
  
  # Drag and drop files from and to Yazi
  { on = "<A-d>", 
    run = '''shell --
          ripdrag --no-click --and-exit --icon-size 64 --target --all "$@" | while read filepath; do cp -nR "$filepath" .; done
          ''', 
    desc = "Drag-n-drop files from and to Yazi, no overwrites" 
  },
  { on = "<A-D>",
    run = '''shell --
          ripdrag --no-click --and-exit --icon-size 64 --target --all "$@" | while read filepath; do cp -fR "$filepath" .; done
          ''', 
    desc = "Drag-n-drop files to and from Yazi, overwrites"
  },
  {
    on = "!",
    for = "unix",
    run = 'shell "$SHELL" --block',
    desc = "Open $SHELL here"
  },
  {
    on = "y",
    run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
  },
]
