#!/bin/bash

DATE=$(LC_ALL=C date | awk '{print $1",",$2, $3".", $6}')
CDATE=$(date "+%d-%m-%Y")
FILE=~/agenda/$CDATE.md

touch $FILE
echo "# $DATE"     >> $FILE
echo ""            >> $FILE
echo "## Water"    >> $FILE
echo ""            >> $FILE
echo "- [ ] "      >> $FILE
echo ""            >> $FILE
echo "- [ ] "      >> $FILE
echo ""            >> $FILE
echo "- [ ] "      >> $FILE
echo ""            >> $FILE
echo "## Exercise" >> $FILE
echo ""            >> $FILE
echo "- [ ]"       >> $FILE

exit
