#!/bin/bash

pacget(){
    ST=$(pacman -Sql | fzf)
    [ -n $ST ] && sudo pacman -S $ST
}
yayget(){
    ST=$(yay -Sql | fzf)
    [ -n $ST ] && yay -S $ST
}

case "$1" in
"pacman")
    $(pacget);;
"yay") 
    $(yayget);;
esac
