#!/bin/bash

file=$(readlink -f "$1")
base=$(echo "$file" | sed 's/..*\///; s/\...*//')

handlebang () {
    bang=$(head -n 1"$file")
    case "$bang" in
        *!/bin/sh|*!/bin/zsh|*/bin/bash) "$file" ;;
        *!/bin/perl) perl "$file" ;;
        *!/bin/python) python "$file" ;;
        *) echo "Can't compile" ;;
    esac
}

case "$1" in
    *.md) pandoc "$file" -o "$base".pdf --pdf-engine=xelatex;;
    *.py) python "$file" ;;
    *.perl) perl "$file" ;;
    *) handlebang ;;
esac
