#!/bin/bash

# Get user selection via dmenu from emoji file.
#chosen=$(cut -d ';' -f1 ~/.dmenu/scripts/emoji | dmenu -i -l 30 | sed "s/ .*//")
chosen=$(cut -d ';' -f1 $HOME/.scripts/emoji | rofi -dmenu | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	ydotool type "$chosen"
else
	# echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	echo "$chosen" | tr -d '\n' | wl-copy
	notify-send "'$chosen' copied to clipboard." &
fi
