#!/usr/bin/bash

theme=$1
kittyconf=~/.config/kitty/kitty.conf

if [ $theme == "dark" ]; then
  sed -i 's/GruvboxLightSoft.conf/GruvboxDarkSoft.conf/g' $kittyconf && kill -s USR1 $(pgrep kitty)
else
  sed -i 's/GruvboxDarkSoft.conf/GruvboxLightSoft.conf/g' $kittyconf && kill -s USR1 $(pgrep kitty)
fi
