#!/bin/bash

vol=$(amixer get Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "MM" } else { print $2 }}' | head -n 1)
pipe="/tmp/volumebar"

#pactl list sinks | grep "Volume: front" | awk '{print $5}' | sed 's/%//g' >> $pipe
echo "$vol" >> $pipe
