use_nerdfont = true
notify = false
gapless = true
volnorm = true
flip_status_indicators = true

[keybindings]
# Movement
"1"  = "focus queue"
"2"  = "focus library"
"3"  = "focus search"
"F1" = "focus queue"
"F2" = "focus library"
"F3" = "focus search"
"G"  = "move bottom"
"g"  = "move top"
"q"  = "back"
"Q"  = "quit"

# Queue Manipulation
"J" = "shift down 1"
"K" = "shift up 1"

[track_format]
left = "%artists | %title"
center = "%album"
right = "%saved %duration"
