#!/usr/bin/bash

hyprconfig=~/.config/hypr/hyprland.conf

# Change window border colors
sed -i 's/98971a/b8bb26/g' $hyprconfig 
sed -i 's/076678/83a598/g' $hyprconfig 

sed -i 's/f2e5bc/282828/g' $hyprconfig
