#!/usr/bin/bash

niriconfig=~/.config/niri/config.kdl

# Change window border colors
sed -i 's/98971a/b8bb26/g' $niriconfig
sed -i 's/076678/83a598/g' $niriconfig

sed -i 's/f2e5bc/282828/g' $niriconfig
