#!/usr/bin/bash

swayconfig=~/.config/sway/config

# Change statusline colors
sed -i 's/statusline \#3c3836/statusline #ebdbb2/g' $swayconfig 
sed -i 's/background \#f2e5bc/background #282828/g' $swayconfig 
sed -i 's/inactive_workspace \#f2e5bc \#f2e5bc \#79740e/inactive_workspace \#282828 \#282828 \#b8bb26/g' $swayconfig 
sed -i 's/focused_workspace \#79740e \#79740e \#f2e5bc/focused_workspace \#b8bb26 \#b8bb26 \#282828/g' $swayconfig 
sed -i 's/active_workspace \#f2e5bc \#f2e5bc \#427b58/active_workspace \#282828 \#282828 \#8ec07c/g' $swayconfig 
sed -i 's/binding_mode \#9d0006 \#9d0006 \#f2e5bc/binding_mode \#fb4934 \#fb4934 \#282828/g' $swayconfig 

# Change window border colors
sed -i 's/client\.focused \#79740e \#79740e \#f2e5bc \#427b58/client\.focused \#b8bb26 \#b8bb26 \#282828 \#8ec07c/g' $swayconfig
sed -i 's/client\.focused_inactive \#689d6a \#689d6a \#f2e5bc \#427b58/client\.focused_inactive \#689d6a \#689d6a \#282828 \#8ec07c/g' $swayconfig
sed -i 's/client\.unfocused \#f2e5bc \#f2e5bc \#79740e \#427b58/client\.unfocused \#282828 \#282828 \#b8bb26 \#8ec07c/g' $swayconfig

# Change wallpaper
sed -i 's/succulent/sleepyplant/g' $swayconfig
sed -i 's/pokewoods/trainstation/g' $swayconfig

swaymsg reload
