#!/usr/bin/bash

waybarconf=~/.config/waybar/style.css
hyprconf=~/.config/waybar/hyprstyle.css

sed -i 's/\@gruvboxLight/\@gruvboxDark/g' $waybarconf
sed -i 's/\@gruvboxLight/\@gruvboxDark/g' $hyprconf

killall -SIGUSR2 waybar
